### ISSUE TITLE
User search returns null for channel

### ISSUE THREAD

**Issue by Turkey2349** [MCProHosting/beam-client-java#10]
When searching for a user it successfully returns the user, but the channel variable for the user always returns null.

**Comment by ttaylorr** [comment]
User searches only return the name and ID of a user.  To populate the rest
of the variables, you'll have to use the findOne method of the UserService
to get the entire user.  The argument that you'll pass to the findOne
method is the ID of the user, as given by the search response, and the
callback to findOne will return the rest of the data associated with that
user.

On Wed, Mar 18, 2015 at 7:12 PM, Turkey2349 <notifications@github.com>
wrote:

> When searching for a user it successfully returns the user, but the
> channel variable for the user always returns null.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MCProHosting/beam-client-java/issues/10>.
>



-- 
Thanks,
Taylor Blau

ttaylorr.com

**Comment by Turkey2349** [comment]
Thank you!

**Comment by Turkey2349** [comment]
you may want to specify this with a javadoc comment or something.

**Comment by ttaylorr** [comment]
No problem!  I absolutely agree, writing Javadocs is one of my to-do's for
this weekend :)

On Wed, Mar 18, 2015 at 7:17 PM, Turkey2349 <notifications@github.com>
wrote:

> you may want to specify this with a javadoc comment or something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MCProHosting/beam-client-java/issues/10#issuecomment-83221150>
> .
>



-- 
Thanks,
Taylor Blau

ttaylorr.com
