### ISSUE TITLE
No way to get the moderators of a channel.

### ISSUE THREAD

**Issue by Turkey2349** [MCProHosting/beam-client-java#11]
Not sure if there is a way to do this yet, but from the little looking i did, there seems to be no way to get the mods of a channel. This would be a very helpful feature to have for bots that have mod only commands and such.

**Comment by ttaylorr** [comment]
Yes, currently there is no endpoint (neither in the client nor on `v1` of our API) to get all users in a specific role related to a channel.  However, I don't think this is a problem.  I assume you want to verify a user has permission before running a command in response to a message.  If this is the case, you can just check the role of the sender in the IncomingMessageData like such:

```java
chatConnectable.on(IncomingMessageEvent.class, new EventHandler<IncomingMessageEvent>() {
  @Override public void onEvent(IncomingMessageEvent event) {
    if (event.data.user_role.equals("mod")) {
      // mod-only things
    }
  }
});
```

**Comment by connor4312** [comment]
@Turkey2349 we have a permissions management system on the radar which will entail endpoints to get all users who have non-default channel roles.

**Comment by Pocketpac** [comment]
There is a way to detect who is a mod on a IncomingMessageEvent which is event.data.user_role

**Comment by ttaylorr** [comment]
Yup, exactly!

On Thu, Mar 19, 2015 at 3:35 PM, Pocketpac <notifications@github.com> wrote:

> There is a way to detect who is a mod on a IncomingMessageEvent which is
> event.data.user_role
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MCProHosting/beam-client-java/issues/11#issuecomment-83734075>
> .
>



-- 
Thanks,
Taylor Blau

ttaylorr.com
