### ISSUE TITLE
PATCH

### ISSUE THREAD

**Issue by njb-said** [MCProHosting/beam-client-java#23]
There doesn't appear to be a method to send patch requests to the api, therefore making it not possible to change a user role or ban/unban someone.

**Comment by Pocketpac** [comment]
https://developer.beam.pro/api/channel/roleUpdate << Here you go

**Comment by njb-said** [comment]
@Pocketpac I know, but the client doesn't support sending patch requests. Hence the point of this issue :wink:

**Comment by Pocketpac** [comment]
Ah, ya there is a lot the client dosnt support still, it is a WIP

**Comment by ttaylorr** [comment]
Fixed in 1ac8597 :smile:
