### ISSUE TITLE
Practical Example of the HTTP methods?

### ISSUE THREAD

**Issue by Pocketpac** [MCProHosting/beam-client-java#24]
Could you provide a practical example on how to use, for example, the PUT method to change the name of your channel?

**Comment by Pocketpac** [comment]
Never mind, all it takes is for me to ask for my brain to say "I dont need no stinkin help, I got this"
For those of you who may read this in the future, this is how you make it change channel name:

                                                String path = BeamAPI.BASE_PATH.resolve("channels/" + ChanID).toString();
                                                ImmutableMap.Builder<String, Object> arguments = BeamHttpClient.getArgumentsBuilder();
                                                arguments.put("name", fuseArray(msg, 1));
                                                beam.http.put(path, BeamChannel.class, arguments.build());

**Comment by ttaylorr** [comment]
Eventually we want to have this sort of stuff abstracted away into services, but that will do exactly what you need it to do for now :)

**Comment by Pocketpac** [comment]
This way is making me learn things, so dont make it to simple ;-)
