### ISSUE TITLE
Emoticons not creating event

### ISSUE THREAD

**Issue by Pocketpac** [MCProHosting/beam-client-java#5]
Now that the url event is fixed emoticon have stopped creating an event. Also, back when they did it was a default/23j3hew type thing instead of the actual emoticon

**Comment by Pocketpac** [comment]
I was able to get it back to accepting emoticons (well, the url representation of them anyway) and was just curious if you had any kind of timeline as to when this issue might be resolved? I understand its the weekend so I not trying to put pressure, but the moderation is all done accept for link protection because I cant test against it, and I can make commands with links and so on. All I need is for this last little bit to be fixed and I can start pushing it publicly.

**Comment by Pocketpac** [comment]
I was able to get it to show all three types, not just pick two. You can commit this to your code if you wish, its simple and elegant IMHO, and above all, it works ;-)

http://bit.ly/1Gz3KiE

**Comment by Pocketpac** [comment]
Also it shows the proper emoticon vs the path to the image.

**Comment by Pocketpac** [comment]
This code might be easier to read for ya. http://bit.ly/1GkKge7

**Comment by ttaylorr** [comment]
Yup, just some incorrect property access causing one of the `Function`s in the `Iterators#transform` call to return null, propagating the `Throwable` up the stack.  Fixed in 95c4d7df7e2b6f0bc1d91f34f90e05bd740ca355 :smile:
