### ISSUE TITLE
Randomly stops receiving messages

### ISSUE THREAD

**Issue by Pocketpac** [MCProHosting/beam-client-java#6]
After a lot of testing and trying to track down the issue, I have discovered the api either looses auth or totally disconnects from the servers. The reason why I know it is the api is because I set it to create a new connection vs sharing a single connection (which is how I had it original, made it create new connections as a test), and some channels will randomly stop while others continue. I am unsure how to go about dealing with this situation.

**Comment by Pocketpac** [comment]
I noticed a cookie error as error codes were flying by when I put a dump on the OnError method. I got looking and may not have been properly sharing the connection. I redid my end of things and it seems stable now. I will keep you apprised.

**Comment by Pocketpac** [comment]
Ok I'm pretty sure it is now sharing the connection because it not joins channels much slower. It joins 4 channels really fast then slowly join 1 channel every 30 seconds or so. Any idea what that is all about?

**Comment by Pocketpac** [comment]
If your curious what I did, here is the last commit that includes the updated changes to properly share a single connection/cookie http://bit.ly/1BZdxhb

**Comment by ttaylorr** [comment]
If the issue persists, keep me posted.  I have a plausible theory on what's happening here, and would be happy to look into it.

**Comment by Pocketpac** [comment]
It is still happening. It happens slowly, 1 channel drops then another than another. No idea whats going on but this is a pretty bad bug. I had a couple peoplle go to have it join their channel and it didnt respond, looks very bad. Please if you could look into this let me know.

**Comment by ttaylorr** [comment]
Will take a look at this as soon as I can :smile:

**Comment by Pocketpac** [comment]
I have confirmed it to not be directly related to the java api @ttaylorr_b when it comes to disconnect. Artguy built a bot using node.js and has the same issue. He is dealing with it by reconnecting everytime it drops. I'm looking into a way to do that as well.

**Comment by Pocketpac** [comment]
Is this something you can implement into the api? Just have it reconnect on a drop.

**Comment by ttaylorr** [comment]
After some investigating, I'm pretty sure that this issue is caused by CloudFlare dropping and then reconnecting the WSS connection.  In previous versions, the client ignored disconnects silently, but now I have it try and reconnect to a different endpoint if it drops the connection.  This regression should be handled properly in 2db5a539deb13546bf4131695e5607d949d8b73e :smile:.

**Comment by Pocketpac** [comment]
Aww man and I had JUST finished an elegant way to handle this. Had a watcher thread watching events, and if 3 were missed in a row it would reconnect. But this works to, I will test it out.

**Comment by Pocketpac** [comment]
Can you please make it so it shows the text form for the emoticon instead of the path. Having the path is useless in most instances.
