### ISSUE TITLE
'_' being used as a wildcard charcter in the user search

### ISSUE THREAD

**Issue by Thelonedevil** [MCProHosting/beam-client-java#9]
As the issue title suggests, I followed the example code, and searched for "the_l", expecting of course my username, and maybe a couple of others to come up, I instead get 

thebladeoftruth
TheFlashPlays
The_Lone_Devil
The_Lost_Boys

Now the bottom two i would expect, they match the search query, however the top two do not.

Now of course using '_' as a wild card operator would be fine, if usernames could not contain it, but they can, hence the issue.

**Comment by ttaylorr** [comment]
Huh, that's some pretty odd behavior!  I'm gonna /cc @connor4312 in on this one, since he probably wrote this endpoint.

**Comment by ttaylorr** [comment]
Yup, this is our API using `_` as a wildcard, so I'm going to create a ticket for it, and I'll update this issue once we've resolved it.  Thanks for creating this issue! :smile:

**Comment by Thelonedevil** [comment]
You are welcome :)

**Comment by connor4312** [comment]
This has been fixed in beam@796ae39, and should be deployed in the coming days.
